# Setting a quick way to reload config
bind r source-file ~/.tmux.conf

# Allowing mouse control, moving status bar to top
set -g mouse on
set -s escape-time 0
set -g status-position top

# Customizing status bar colors & adding battery percentage to status bar
set-option -g status-style "bg=black"
set-window-option -g status-right "#[bg=green,fg=black] %a %d #[bg=blue] %H:%M #[bg=cyan] #(acpi -b | grep -m1 -o -P '.{0,2}%') "

# Vim keys for navigating panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Adding keybindings for adjusting brightness
bind -n F8 run-shell 'brightnessctl -q set 5%-'
bind -n F9 run-shell 'brightnessctl -q set +5%'
