#!/usr/bin/env bash

echo United States COVID-19 updates:
grep "USA (US)" ~/.bin/assets/corona | 
    sed "s/ //g ; s/║//g ; s/│/:/g ; s/▲//g" |
    awk -F ':' '{print $3 " Confirmed cases, resulting in " $5 " deaths. " "\n" "Up " $4 " since yesterday. " $7 " recovered."}'
