#!/usr/bin/env bash

curl -s https://corona-stats.online/us > ~/.bin/assets/corona

echo Texas COVID-19 updates:
grep "Texas" ~/.bin/assets/corona | 
    sed "s/ //g ; s/║//g ; s/│/:/g ; s/▲//g" | 
    awk -F ':' '{print $3 " Confirmed cases, resulting in " $5 " deaths. " "\n" $8 "% Recovered. Up " $9 " since yesterday."}'

# This script was shamelessly ripped off from Luke Smith: https://lukesmith.xyz
# Feel free to copy script, and update it to provide info on your state by 
# If you like the script, please send any thanks to Luke Smith, here is a link 
# to the original video: https://www.youtube.com/watch?v=cQ03v4d3QEo
