#!/usr/bin/env bash

yay -Sy
alias w='feh --bg-fill --randomize ~/Media/wallpapers-ii/wallpapers/'

#||\\ //||
#|| \// || Mackenzie Criswell
#|| //\ || https://makc.co
#||   \\|| https://github.com/makccr
