#!/usr/bin/env bash

case "$1" in
    -help) less ~/.bin/assets/dir.txt ;;
esac

echo Making directory: $1...
mkdir $1
cd $1
echo Succesful. && echo ' '
#Making base directory, and naming it with first argument

echo Setting up folder strcuture...
mkdir assets project render script #Setting up basic folder structure

cd script
git init -q
cp ~/Movies/graphicsPackage/script.fountain .
mv script.fountain $1.fountain #Setting up a git controlled fountain script

cd ../assets
mkdir aRoll bRoll thumb branding
cd aRoll
mkdir image motion audio
cd ../bRoll
mkdir image motion audio
cd ../thumb
mkdir image motion audio
cd ../branding
mkdir image motion 
#Setting up the rest of the folder structure

cd ../../ #Backing out to base level directory

echo Succesful. && echo ' ' 

echo Copying neccisary assets...

case "$2" in 
    -i) cd assets/branding
        cp -r ~/Movies/graphicsPackage/music . && 
        mv music audio &&
        cd motion && 
        cp ~/Movies/graphicsPackage/branding/intro.mov . && 
        cp ~/Movies/graphicsPackage/branding/endCard.mov . 
        cd ../../../
        ;; #Copying over Intro, Endcard, & Music
    -p) cd project && 
        cp ~/Movies/premiereTemplate/project/Template.prproj . && 
        mv Template.prproj $1.prproj &&
        cd ../
        ;; #Copying over the Premiere Pro Template, renaming
    -f) cd project && 
        cp -r ~/Movies/youtubeTemplate.fcpbundle . && 
        mv youtubeTemplate.fcpbundle $1.fcpbundle 
        cd ../
        ;; #Copying over the Final Cut Template, renaming
    -n) rm -rf script &&
        cd assets &&
        rm -rf branding && 
        cd ../
        ;; #Removing script & branding folder, not necessary for non YouTube
esac

case "$3" in
    -p) cd project && 
        cp ~/Movies/premiereTemplate/project/Template.prproj . && 
        mv Template.prproj $1.prproj &&
        cd ../
        ;; #Copying over the Premiere Pro Template, renaming
esac

echo Succesful. && echo ' '
echo Done. 
