#!/usr/bin/env bash

echo 'Updating Applications...'
    brew upgrade         
    brew update #Updating home-brew apps & formulas
    brew cask upgrade #Updating apps installed as Casks
    mas upgrade #Updating Mac App Store Apps
    npm update #You know...
echo 'Cleaning caches & directories...'
    brew cleanup -s #Clearing home-brew cache
echo 'Updating Complete!'
