#!/usr/bin/env bash

# Setting up basic monitor settings
xrandr --output "HDMI1" --mode "1440x900"
xrandr --output "VGA1" --mode "1366x768"
xrandr --output "HDMI1" --auto --output "VGA1" --right-of "HDMI1"

# Setting up recording resolutions
xrandr --newmode "1920x960_60.00"  152.00  1920 2032 2232 2544  960 963 973 996 -hsync +vsync
xrandr --addmode HDMI1 "1920x960_60.00"
xrandr --addmode VGA1 "1920x960_60.00"

# Fixing Wallpapers
feh --bg-fill --randomize ~/Media/wallpapers/backgrounds

#||\\ //||
#|| \// || Mackenzie Criswell
#|| //\ || https://makc.co
#||   \\|| https://github.com/makccr
