#!/usr/bin/env bash

# Setting up basic monitor settings
xrandr --output "LVDS-1" --mode "1600x900"
xrandr --output "VGA-1" --mode "1366x768"
xrandr --output "LVDS-1" --auto --output "VGA-1" --right-of "LVDS-1"

# Setting up recording resolutions
xrandr --newmode "1920x960_60.00"  152.00  1920 2032 2232 2544  960 963 973 996 -hsync +vsync
xrandr --addmode LVDS-1 "1920x960_60.00"
xrandr --addmode VGA-1 "1920x960_60.00"

# Fixing Wallpapers
feh --bg-fill --randomize ~/Media/wallpapers/backgrounds

#||\\ //||
#|| \// || Mackenzie Criswell
#|| //\ || https://makc.co
#||   \\|| https://github.com/makccr
