general {
    grace = 0
    disable_loading_bar = true
}

background {
    monitor =
    path = screenshot
    color = rgba(0, 0, 0, 1.0)
    blur_passes = 4
}

input-field {
    monitor =
    size = 15%, 4%
    outline_thickness = 1
    inner_color = rgba(0, 0, 0, 0.2) # no fill

    outer_color = rgb(aaaaaa)
    check_color=rgb(81a1c1)
    fail_color=rgb(bf616a)

    font_color = rgb(e5e9f0)
    fade_on_empty = false
    rounding = 50

    position = 0, 0
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = rgba(200, 200, 200, 1.0)
    font_size = 60
    font_family = Hack Nerd Fonts
    font_color = rgb(e5e9f0)
    position = 0, 125
    halign = center
    valign = center
}

label {
    monitor =
    text = poweroff
    color = rgba(200, 200, 200, 1.0)
    onclick = poweroff
    font_size = 25
    font_family = Hack Nerd Fonts
    font_color = rgb(e5e9f0)
    position = 0, -725
    halign = center
    valign = center
}

label {
    monitor =
    text = reboot
    color = rgba(200, 200, 200, 1.0)
    onclick = reboot
    font_size = 25
    font_family = Hack Nerd Font
    font_color = rgb(e5e9f0)
    position = 0, -675
    halign = center
    valign = center
}
