#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap           15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

## Autostart
sh $HOME/.config/polybar/bspwm.sh &
picom &
dunst &
udiskie &
dropbox &
flameshot &
xbindkeys &
transmission-daemon &
feh --bg-fill -r -z ~/Pictures/wallpapers/wallpapers &
xrandr --output eDP-1 --mode 1920x1080 &
