#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xset -dpms
xset s off

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Firefox focus=on
bspc rule -a Firefox pointer=on

## Autostart
sh $HOME/.config/polybar/bspwm.sh &
picom &
dunst &
udiskie &
dropbox &
flameshot &
xbindkeys &
transmission-daemon &
feh --bg-fill -r -z ~/Pictures/wallpapers/wallpapers/art &
xrandr --output eDP-1 --mode 1920x1080 &
redshift -l 29.536997852:-95.018166594 &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
