[colors]
draw_bold_text_with_bright_colors = false

[general]
import = [
    "~/.config/alacritty/themes/material_ocean.toml"
]

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.selection]
background = "0xdc3232"
text = "0xffffff"

[cursor.style]
blinking = "off"
shape = "Beam"

[font]
size = 12

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "Full"
opacity = 0.95

[window.dimensions]
columns = 150
lines = 45

[window.padding]
x = 15
y = 15
