[colors]
draw_bold_text_with_bright_colors = true

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = '0x4C566A'
red = '0xBF616A'
green = '0xA3BE8C'
yellow = '0xEBCB8B'
blue = '0x81A1C1'
magenta = '0xB48EAD'
cyan = '0x88C0D0'
white = '0xE5E9F0'

[colors.primary]
background = "0x0f111a"
foreground = "0xD8DEE9"

[colors.selection]
background = "0xdc3232"
text = "0xffffff"

[cursor.style]
blinking = "off"
shape = "Beam"

[font]
size = 12

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "Full"
opacity = 1

[window.dimensions]
columns = 150
lines = 45

[window.padding]
x = 15
y = 15
