#!/usr/bin/env bash

bold=$(tput bold)
normal=$(tput sgr0)
packages=$(sudo ls /var/cache/pacman/pkg/ | wc -l)
size=$(du -sh /var/cache/pacman/pkg/)

sudo -v

echo "${bold}Updating packages from Pacman and the AUR...${normal}"
echo " "
yay

echo "Clearing ${bold}${packages}${normal} packages, totaling ${bold}${size}${normal}..."
echo " "

sudo pacman -Scc
yay -Scc

echo "${bold}Pulling down any new dotfiles...${normal}"
echo " "

cd ~/Repo/dot
git pull
cd ~

echo "${bold}Updating Done.${normal}"
