#!/usr/bin/env bash

date +"%R - %a, %B %d, %Y"; 
echo "###### journal";
echo "###### soliloquy";
echo "###### health";
echo "###### common place";
echo "###### maintenance";
echo "###### essay";
echo "###### diary";
echo "###### failure";
echo "###### success ";
echo "###### dream";
echo "###### tech"
