#!/usr/bin/env bash

echo 'Apps to update:'
brew outdated
brew outdated --cask --greedy
mas outdated

echo ' ' 
echo 'Updating Applications...'
    brew upgrade         
    brew update #Updating home-brew apps & formulas
    brew cask upgrade --greedy #Updating apps installed as Casks
    mas upgrade #Updating Mac App Store Apps
    npm update #You know...

echo ' ' 
echo 'Cleaning caches & directories...'
    brew cleanup -s #Clearing home-brew cache
     rm -rf /private/var/folders/17/0n1s76yx0m93869jhvbc_5hh0000gn/C/com.apple.appstoreagent

echo ' ' 
echo 'Updating Complete!'
